echo:
	cd cmd/echo && \
	go build -o echo && \
	cd - && \
	mv cmd/echo/echo bin

clean-echo:
	rm bin/echo

unique-ids:
	cd cmd/unique-ids && \
	go build -o unique-ids && \
	cd - && \
	mv cmd/unique-ids/unique-ids bin

clean-unique-ids:
	rm bin/unique-id
